dependencies:
- alabaster=0.7.6=py35_0
- babel=2.1.1=py35_0
- colorama=0.3.3=py35_0
- cycler=0.9.0=py35_0
- decorator=4.0.4=py35_0
- docutils=0.12=py35_0
- freetype=2.5.5=0
- ipykernel=4.1.1=py35_0
- ipython-notebook
- jinja2=2.8=py35_0
- jsonschema=2.4.0=py35_0
- jupyter_client=4.1.1=py35_0
- jupyter_core=4.0.6=py35_0
- libpng=1.6.17=0
- markupsafe=0.23=py35_0
- matplotlib=1.5.0=np110py35_0
- mistune=0.7.1=py35_0
- nbconvert=4.0.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.0.6=py35_0
- numpy=1.10.1=py35_0
- openssl=1.0.2d=0
- pandas=0.17.1=np110py35_0
- path.py=8.1.2=py35_1
- pexpect=3.3=py35_0
- pickleshare=0.5=py35_0
- pip=7.1.2=py35_0
- ptyprocess=0.5=py35_0
- pygments=2.0.2=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_0
- python=3.5.0=1
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- pyyaml=3.11=py35_1
- pyzmq=14.7.0=py35_1
- qt=4.8.7=1
- readline=6.2=2
- setuptools=18.5=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.0=py35_0
- sphinx=1.3.1=py35_0
- sphinx_rtd_theme=0.1.7=py35_0
- sqlite=3.8.4.1=1
- terminado=0.5=py35_1
- tk=8.5.18=0
- tornado=4.3=py35_0
- traitlets=4.0.0=py35_0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- yaml=0.1.6=0
- zeromq=4.1.3=0
- zlib
- pip:
  - cloud-sptheme==1.7
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-core==4.0.6
  - latexcodec==1.0.1
  - oset==0.1.3
  - pybtex==0.19
  - pybtex-docutils==0.2.1
  - sphinx-rtd-theme==0.1.7
  - sphinxcontrib-bibtex==0.3.3

