dependencies:
- alabaster=0.7.6=py35_0
- babel=2.1.1=py35_0
- cycler=0.9.0=py35_0
- decorator=4.0.6=py35_0
- docutils=0.12=py35_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- ipykernel=4.2.2=py35_0
- ipython=4.0.2=py35_0
- ipython-notebook=4.0.4=py35_0
- ipython_genutils=0.1.0=py35_0
- jinja2=2.8=py35_0
- jsonschema=2.4.0=py35_0
- jupyter_client=4.1.1=py35_0
- jupyter_core=4.0.6=py35_0
- libgfortran=1.0=0
- libpng=1.6.17=0
- libsodium=1.0.3=0
- libxml2=2.9.2=0
- markupsafe=0.23=py35_0
- matplotlib=1.5.1=np110py35_0
- mistune=0.7.1=py35_0
- nbconvert=4.1.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.1.0=py35_0
- numpy=1.10.2=py35_0
- openblas=0.2.14=3
- openssl=1.0.2e=0
- pandas=0.17.1=np110py35_0
- path.py=8.1.2=py35_1
- pexpect=3.3=py35_0
- pickleshare=0.5=py35_0
- pip=7.1.2=py35_0
- ptyprocess=0.5=py35_0
- pygments=2.0.2=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_1
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- pyzmq=15.2.0=py35_0
- qt=4.8.7=1
- readline=6.2=2
- setuptools=19.2=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.0=py35_0
- sphinx=1.3.1=py35_0
- sphinx_rtd_theme=0.1.7=py35_0
- sqlite=3.9.2=0
- terminado=0.5=py35_1
- tk=8.5.18=0
- tornado=4.3=py35_0
- traitlets=4.0.0=py35_0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - cloud-sptheme==1.7.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-core==4.0.6
  - latexcodec==1.0.1
  - oset==0.1.3
  - pybtex==0.19
  - pybtex-docutils==0.2.1
  - pyyaml==3.11
  - sphinx-rtd-theme==0.1.7
  - sphinxcontrib-bibtex==0.3.3

