channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >= 3.7
  - pip
  - setuptools_scm
  - toml

  # Documentation
  - furo
  - ipython
  - nbsphinx
  - sphinx
  - sphinx-autoapi
  - sphinx-click
  - sphinx-copybutton
  - sphinx-panels
  - sphinxcontrib-bibtex
