---
name: ept-docs
channels: [conda-forge]
dependencies:
  - python ==3.12
  # Dependencies for building the documentation
  - furo
  - myst-parser
  - nbsphinx
  - pydata-sphinx-theme>=0.3.0
  - sphinx
  - sphinx-autoapi
  - sphinx-click
  - sphinx-copybutton
  - sphinx-panels
  - sphinxcontrib-bibtex
  # Dependencies necessary to generate visualizations for the documentation
  - pytask >=0.5.0
  - python-kaleido
  - plotly >=5.2.0,<6
  - pip
  - pip: [../]
